"""Render the body of a QLint migration pull request as Markdown.

The counterpart of the PR *comment* formatter shipped with the GitHub Action
in F21: same Markdown-table conventions (severity-ordered rows, backticked
paths, a bounded row count, a trailing generated-by marker) applied to a
different question. F21 answers "here is what the scan found"; this answers
"here is what this pull request changed, and what it deliberately did not".

Reuse note: F21's pr_comment_formatter.py is not importable from this
repository -- only a stale __pycache__ artifact of it survives, its source was
never committed -- so the conventions are followed rather than imported. If
that source is ever restored, _table and _cell here are the two functions to
collapse into it.

Like the SARIF and CBOM converters, nothing here raises. A malformed finding
must not fail a pull request whose commit has already landed.
"""

REPO_URL = "https://github.com/Abhushan187/QLint"
FOOTER_MARKER = "Generated by QLint"
BODY_MARKER = "<!-- qlint-pqc-migration-pr -->"

# Long enough for a realistic migration, short enough that the pull request
# stays readable. Rows past this are counted, not printed.
MAX_TABLE_ROWS = 25

SEVERITY_ORDER = ["critical", "warning", "safe", "info"]


def _severity_rank(severity) -> int:
    try:
        return SEVERITY_ORDER.index(str(severity).lower())
    except ValueError:
        return len(SEVERITY_ORDER)


def _text(value, fallback: str = "") -> str:
    if value is None:
        return fallback
    text = str(value).strip()
    return text or fallback


def _cell(value, fallback: str = "-") -> str:
    """One table cell: single-line, pipe-escaped, never empty.

    A raw pipe or newline in a finding field would otherwise split the row and
    silently corrupt every column after it.
    """
    text = _text(value)
    if not text:
        return fallback
    return text.replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    if not rows:
        return []
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows[:MAX_TABLE_ROWS]:
        lines.append("| " + " | ".join(row) + " |")
    if len(rows) > MAX_TABLE_ROWS:
        lines.append("")
        lines.append(f"_...and {len(rows) - MAX_TABLE_ROWS} more._")
    return lines


def _sorted_by_severity(items: list[dict]) -> list[dict]:
    return sorted(
        items,
        key=lambda item: (
            _severity_rank((item.get("finding") or {}).get("severity")),
            _text((item.get("finding") or {}).get("file")),
            (item.get("finding") or {}).get("line") or 0,
        ),
    )


def _applied_rows(applied: list[dict]) -> list[list[str]]:
    rows = []
    for item in _sorted_by_severity(applied):
        finding = item.get("finding") or {}
        rows.append(
            [
                _cell(finding.get("severity")),
                f"`{_cell(finding.get('file'))}`",
                _cell(finding.get("line")),
                _cell(finding.get("algorithm")),
                _cell(finding.get("replacement")),
            ]
        )
    return rows


def _skipped_rows(skipped: list[dict]) -> list[list[str]]:
    rows = []
    for item in _sorted_by_severity(skipped):
        finding = item.get("finding") or {}
        rows.append(
            [
                f"`{_cell(finding.get('file'))}`",
                _cell(finding.get("line")),
                _cell(finding.get("algorithm")),
                _cell(item.get("reason")),
            ]
        )
    return rows


def _files_line(applied: list[dict]) -> str:
    files = sorted(
        {
            _text((item.get("finding") or {}).get("file"))
            for item in applied
            if _text((item.get("finding") or {}).get("file"))
        }
    )
    if not files:
        return "No files were changed."
    listed = ", ".join(f"`{name}`" for name in files)
    plural = "file" if len(files) == 1 else "files"
    return f"{len(files)} {plural} changed: {listed}"


def format_pr_body(
    repo: str,
    applied: list[dict],
    skipped: list[dict],
    scan_id: str | None = None,
) -> str:
    """Markdown for the pull request body. Never raises.

    applied and skipped are lists of {"finding": {...}, "reason": str} -- the
    same shape the endpoint returns to the browser, so the pull request and
    the results screen cannot disagree about what happened.
    """
    try:
        applied = list(applied or [])
        skipped = list(skipped or [])

        lines = [
            "## QLint: post-quantum cryptography migration",
            "",
            f"This pull request migrates quantum-vulnerable cryptography in "
            f"`{_text(repo, 'this repository')}` to post-quantum-safe "
            "equivalents, based on a QLint scan.",
            "",
            f"- **{len(applied)}** finding(s) patched",
            f"- **{len(skipped)}** finding(s) skipped",
            f"- {_files_line(applied)}",
            "",
        ]

        applied_rows = _applied_rows(applied)
        if applied_rows:
            lines.append("### Changes in this pull request")
            lines.append("")
            lines.extend(
                _table(
                    ["Severity", "File", "Line", "Algorithm", "Replacement"],
                    applied_rows,
                )
            )
            lines.append("")

        skipped_rows = _skipped_rows(skipped)
        if skipped_rows:
            lines.append("### Skipped, and why")
            lines.append("")
            lines.append(
                "These findings were left alone on purpose. QLint re-reads "
                "every file from GitHub before patching it and refuses to "
                "apply a change it cannot place exactly, so a file that "
                "changed since the scan is skipped rather than guessed at."
            )
            lines.append("")
            lines.extend(
                _table(["File", "Line", "Algorithm", "Reason"], skipped_rows)
            )
            lines.append("")

        lines.append("### Before you merge")
        lines.append("")
        lines.append(
            "The replacements are AI-generated and were applied only where "
            "the flagged code still matched the scan exactly. Review the diff "
            "and run your test suite. Closing this pull request without "
            "merging changes nothing in your repository."
        )
        lines.append("")
        lines.append("---")
        footer = f"{FOOTER_MARKER} - <{REPO_URL}>"
        if scan_id:
            footer = f"{footer} (scan `{_cell(scan_id)}`)"
        lines.append(footer)
        lines.append(BODY_MARKER)
        return "\n".join(lines)
    except Exception:  # pragma: no cover - the never-raises guarantee
        return (
            "## QLint: post-quantum cryptography migration\n\n"
            "This pull request was created by QLint.\n\n"
            f"---\n{FOOTER_MARKER} - <{REPO_URL}>\n{BODY_MARKER}"
        )


def format_commit_message(repo: str, applied: list[dict]) -> str:
    """Subject line plus a body listing the files, for the single commit."""
    try:
        count = len(applied or [])
        files = sorted(
            {
                _text((item.get("finding") or {}).get("file"))
                for item in (applied or [])
                if _text((item.get("finding") or {}).get("file"))
            }
        )
        subject = (
            f"Migrate {count} quantum-vulnerable finding"
            f"{'' if count == 1 else 's'} to post-quantum cryptography"
        )
        body = "\n".join(f"- {name}" for name in files)
        return f"{subject}\n\n{body}\n" if body else f"{subject}\n"
    except Exception:  # pragma: no cover - the never-raises guarantee
        return "Migrate quantum-vulnerable cryptography\n"
